FROM chuanwen/cowsay:latest

ENTRYPOINT [ "/usr/games/cowsay" ]

CMD [ "Go Jonathan, Go" ]

#docker container run cowsay -l

#docker image build ./ -t cowsay

#docker container run cowsay

#docker container run cowsay Go Team, Go!

#docker container run cowsay -f moofasa "There you go"
